# Generated by Django 2.0.6 on 2018-06-28 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('addr_x', models.FloatField()),
                ('addr_y', models.FloatField()),
                ('picture', models.FileField(upload_to='pictures/')),
                ('category', models.CharField(choices=[('RS', 'Restaurant Single'), ('RD', 'Restaurant Duo'), ('RP', 'Restaurant Price'), ('CS', 'Cafe Single'), ('CD', 'Cafe Duo'), ('CP', 'Cafe Price'), ('PS', 'Pub Soju'), ('PD', 'Pub Duo'), ('PP', 'Pub Price'), ('HD', 'Hidden Day'), ('HN', 'Hidden Night')], max_length=2)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=None, max_length=100)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='universities.Spot')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('addr_x', models.FloatField()),
                ('addr_y', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='universities.University'),
        ),
    ]
